# Generated by Django 5.2.17 on 2026-08-15 14:29

import bookings.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('held', 'Held'), ('pending_payment', 'Pending payment'), ('confirmed', 'Confirmed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('redeemed', 'Redeemed')], default='held', max_length=32)),
                ('booker_name', models.CharField(max_length=150)),
                ('attendee_names', models.JSONField(validators=[bookings.models.validate_attendee_names])),
                ('total_price_egp', models.PositiveIntegerField()),
                ('total_price_cents', models.PositiveIntegerField()),
                ('hold_expires_at', models.DateTimeField(blank=True, null=True)),
                ('booking_code', models.CharField(blank=True, max_length=16, null=True, unique=True)),
                ('paymob_intention_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('paymob_transaction_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('redeemed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('price_egp', models.PositiveIntegerField()),
                ('price_cents', models.PositiveIntegerField()),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='bookings.booking')),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='slots', to='bookings.court')),
            ],
            options={
                'ordering': ['date', 'start_time'],
                'constraints': [models.UniqueConstraint(fields=('booking', 'date', 'start_time'), name='uniq_booking_slot_start'), models.UniqueConstraint(condition=models.Q(('released_at__isnull', True)), fields=('court', 'date', 'start_time'), name='uniq_active_court_slot')],
            },
        ),
    ]
