/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness check for deploy/tunnel. No auth.
         *
         *     Use this URL in ngrok health checks and as a smoke test after boot.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 200 OK — healthy */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "status": "ok"
                         *     }
                         */
                        "application/json": {
                            status?: string;
                        };
                    };
                };
                /** @description 503 Service Unavailable — database down */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": {
                         *         "code": "UNHEALTHY",
                         *         "message": "Database unavailable"
                         *       }
                         *     }
                         */
                        "application/json": {
                            error?: {
                                code?: string;
                                message?: string;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/courts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List courts
         * @description List the two seeded padel courts. No auth. Save `court_id` from the first item.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 200 OK — two courts */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example [
                         *       {
                         *         "id": "11111111-1111-4111-8111-111111111111",
                         *         "name": "Court 1",
                         *         "slug": "court-1"
                         *       },
                         *       {
                         *         "id": "22222222-2222-4222-8222-222222222222",
                         *         "name": "Court 2",
                         *         "slug": "court-2"
                         *       }
                         *     ]
                         */
                        "application/json": {
                            id?: string;
                            name?: string;
                            slug?: string;
                        }[];
                    };
                };
                /** @description 500 Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": {
                         *         "code": "INTERNAL_ERROR",
                         *         "message": "Unexpected server error"
                         *       }
                         *     }
                         */
                        "application/json": {
                            error?: {
                                code?: string;
                                message?: string;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/slots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List slots
         * @description Generated 08:00–21:00 grid for one court and date.
         *
         *     **States:** `available` | `held` | `booked`. Held slots of other customers are never selectable.
         *
         *     Morning slots include `label: "Morning available"` and a lower `price_egp`.
         *
         *     Book-ahead window: today through 14 days. Slot duration: 60 minutes.
         */
        get: {
            parameters: {
                query?: {
                    /** @example {{slot_date}} */
                    date?: string;
                    /** @example {{court_id}} */
                    court_id?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 200 OK — slot grid */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "date": "2026-08-20",
                         *       "court": {
                         *         "id": "11111111-1111-4111-8111-111111111111",
                         *         "name": "Court 1"
                         *       },
                         *       "operating_hours": {
                         *         "open": "08:00",
                         *         "close": "22:00"
                         *       },
                         *       "slot_minutes": 60,
                         *       "slots": [
                         *         {
                         *           "start_time": "08:00",
                         *           "end_time": "09:00",
                         *           "state": "available",
                         *           "period": "morning",
                         *           "price_egp": 200,
                         *           "price_cents": 20000,
                         *           "label": "Morning available"
                         *         },
                         *         {
                         *           "start_time": "09:00",
                         *           "end_time": "10:00",
                         *           "state": "held",
                         *           "period": "morning",
                         *           "price_egp": 200,
                         *           "price_cents": 20000,
                         *           "label": "Morning available"
                         *         },
                         *         {
                         *           "start_time": "18:00",
                         *           "end_time": "19:00",
                         *           "state": "available",
                         *           "period": "evening",
                         *           "price_egp": 350,
                         *           "price_cents": 35000,
                         *           "label": null
                         *         },
                         *         {
                         *           "start_time": "19:00",
                         *           "end_time": "20:00",
                         *           "state": "booked",
                         *           "period": "evening",
                         *           "price_egp": 350,
                         *           "price_cents": 35000,
                         *           "label": null
                         *         },
                         *         {
                         *           "start_time": "20:00",
                         *           "end_time": "21:00",
                         *           "state": "available",
                         *           "period": "evening",
                         *           "price_egp": 350,
                         *           "price_cents": 35000,
                         *           "label": null
                         *         },
                         *         {
                         *           "start_time": "21:00",
                         *           "end_time": "22:00",
                         *           "state": "available",
                         *           "period": "evening",
                         *           "price_egp": 350,
                         *           "price_cents": 35000,
                         *           "label": null
                         *         }
                         *       ]
                         *     }
                         */
                        "application/json": {
                            /** Format: date */
                            date?: string;
                            court?: {
                                id?: string;
                                name?: string;
                            };
                            operating_hours?: {
                                /** Format: style */
                                open?: string;
                                close?: string;
                            };
                            slot_minutes?: number;
                            slots?: {
                                /** Format: style */
                                start_time?: string;
                                end_time?: string;
                                state?: string;
                                period?: string;
                                price_egp?: number;
                                price_cents?: number;
                                label?: string;
                                held_by_me?: boolean;
                            }[];
                        };
                    };
                };
                /** @description 400 Bad Request — missing date */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error?: {
                                code?: string;
                                message?: string;
                                details?: {
                                    date?: string[];
                                };
                            };
                        };
                    };
                };
                /** @description 404 Not Found — unknown court */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": {
                         *         "code": "NOT_FOUND",
                         *         "message": "Court not found."
                         *       }
                         *     }
                         */
                        "application/json": {
                            error?: {
                                code?: string;
                                message?: string;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/passes/{booking_code}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example MGZ-7F42K */
                booking_code: string;
            };
            cookie?: never;
        };
        /**
         * Get public pass
         * @description Public booking pass. Unlisted — you need the code. Omits phone and Paymob ids. Frontend renders QR from `qr_payload`.
         *
         *     Codes are issued **only after** a verified Paymob webhook, so unpaid holds cannot be looked up here.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @example MGZ-7F42K */
                    booking_code: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 200 OK — confirmed pass */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            booking_code?: string;
                            status?: string;
                            court?: {
                                id?: string;
                                name?: string;
                            };
                            /** Format: date */
                            date?: string;
                            /** Format: style */
                            start_time?: string;
                            end_time?: string;
                            booker_name?: string;
                            attendee_names?: string[];
                            price_egp?: number;
                            /** Format: uri */
                            qr_payload?: string;
                            redeemed_at?: unknown;
                        };
                    };
                };
                /** @description 404 Not Found — unknown or unpaid code */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": {
                         *         "code": "NOT_FOUND",
                         *         "message": "No paid booking for this code."
                         *       }
                         *     }
                         */
                        "application/json": {
                            error?: {
                                code?: string;
                                message?: string;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register
         * @description Create a customer account. Phone is the unique identifier (`01xxxxxxxxx`, 11 digits). Password min 6 characters. Always `role: customer`.
         *
         *     On success, tokens are returned so the client can book immediately.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    /**
                     * @example {
                     *       "name": "Ahmed Hassan",
                     *       "phone": "1012345678",
                     *       "password": "secret12"
                     *     }
                     */
                    "application/json": {
                        name?: string;
                        /** Format: utc-millisec */
                        phone?: string;
                        password?: string;
                    };
                };
            };
            responses: {
                /** @description 201 Created — account + tokens */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "access": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.access",
                         *       "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.refresh",
                         *       "token_type": "Bearer",
                         *       "expires_in": 3600,
                         *       "user": {
                         *         "id": "9b1deb4d-3b7d-4bad-9bdd-2b0d7b3dcb6d",
                         *         "name": "Ahmed Hassan",
                         *         "phone": "01012345678",
                         *         "role": "customer"
                         *       }
                         *     }
                         */
                        "application/json": {
                            access?: string;
                            refresh?: string;
                            token_type?: string;
                            expires_in?: number;
                            user?: {
                                id?: string;
                                name?: string;
                                /** Format: utc-millisec */
                                phone?: string;
                                /** @enum {string} */
                                role?: "customer" | "staff";
                            };
                        };
                    };
                };
                /** @description 400 Bad Request — invalid phone */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error?: {
                                code?: string;
                                message?: string;
                                details?: {
                                    phone?: string[];
                                };
                            };
                        };
                    };
                };
                /** @description 409 Conflict — phone taken */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": {
                         *         "code": "PHONE_TAKEN",
                         *         "message": "An account with this phone already exists."
                         *       }
                         *     }
                         */
                        "application/json": {
                            error?: {
                                code?: string;
                                message?: string;
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Phone + password → JWT access and refresh. Same endpoint for customers and staff; `user.role` is the only difference.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    /**
                     * @example {
                     *       "phone": "1012345678",
                     *       "password": "secret12"
                     *     }
                     */
                    "application/json": {
                        /** Format: utc-millisec */
                        phone?: string;
                        password?: string;
                    };
                };
            };
            responses: {
                /** @description 200 OK — tokens */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "access": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.access",
                         *       "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.refresh",
                         *       "token_type": "Bearer",
                         *       "expires_in": 3600,
                         *       "user": {
                         *         "id": "9b1deb4d-3b7d-4bad-9bdd-2b0d7b3dcb6d",
                         *         "name": "Ahmed Hassan",
                         *         "phone": "01012345678",
                         *         "role": "customer"
                         *       }
                         *     }
                         */
                        "application/json": {
                            access?: string;
                            refresh?: string;
                            token_type?: string;
                            expires_in?: number;
                            user?: {
                                id?: string;
                                name?: string;
                                /** Format: utc-millisec */
                                phone?: string;
                                /** @enum {string} */
                                role?: "customer" | "staff";
                            };
                        };
                    };
                };
                /** @description 400 Bad Request — missing fields */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": {
                         *         "code": "VALIDATION_ERROR",
                         *         "message": "Invalid request body",
                         *         "details": {
                         *           "password": [
                         *             "This field is required."
                         *           ]
                         *         }
                         *       }
                         *     }
                         */
                        "application/json": {
                            error?: {
                                code?: string;
                                message?: string;
                                details?: {
                                    password?: string[];
                                };
                            };
                        };
                    };
                };
                /** @description 401 Unauthorized — bad credentials */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": {
                         *         "code": "INVALID_CREDENTIALS",
                         *         "message": "Phone or password is incorrect."
                         *       }
                         *     }
                         */
                        "application/json": {
                            error?: {
                                code?: string;
                                message?: string;
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh token
         * @description Exchange a valid refresh token for a new access token.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    /**
                     * @example {
                     *       "refresh": ""
                     *     }
                     */
                    "application/json": {
                        refresh?: string;
                    };
                };
            };
            responses: {
                /** @description 200 OK — new access token */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "access": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.access",
                         *       "token_type": "Bearer",
                         *       "expires_in": 3600
                         *     }
                         */
                        "application/json": {
                            access?: string;
                            token_type?: string;
                            expires_in?: number;
                        };
                    };
                };
                /** @description 401 Unauthorized — invalid refresh */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": {
                         *         "code": "UNAUTHENTICATED",
                         *         "message": "Refresh token is invalid or expired."
                         *       }
                         *     }
                         */
                        "application/json": {
                            error?: {
                                code?: string;
                                message?: string;
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Me
         * @description Current profile. Requires a JWT. Includes `role` (`customer` or `staff`).
         */
        get: {
            parameters: {
                query?: never;
                header?: {
                    /** @example Bearer {{access_token}} */
                    Authorization?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 200 OK — profile */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "id": "9b1deb4d-3b7d-4bad-9bdd-2b0d7b3dcb6d",
                         *       "name": "Ahmed Hassan",
                         *       "phone": "01012345678",
                         *       "role": "customer"
                         *     }
                         */
                        "application/json": {
                            id?: string;
                            name?: string;
                            /** Format: utc-millisec */
                            phone?: string;
                            /** @enum {string} */
                            role?: "customer" | "staff";
                        };
                    };
                };
                /** @description 401 Unauthorized — missing or expired JWT */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": {
                         *         "code": "UNAUTHENTICATED",
                         *         "message": "Authentication credentials were not provided."
                         *       }
                         *     }
                         */
                        "application/json": {
                            error?: {
                                code?: string;
                                message?: string;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bookings/hold": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Hold slots
         * @description Atomically hold 1–4 consecutive 60-minute slots for 10 minutes.
         *
         *     `slots` is a list of `{ court_id, date, start_time }` objects (e.g. 18:00 and 19:00 holds 18:00–20:00). Hours must share one court and date, be unique, and be consecutive. Price is the sum of each hour's band.
         *
         *     Creates one `held` booking. Occupies every hour: unique on `court + date + start_time` per occupied hour (active statuses only).
         *
         *     **Attendee names** are required (1–4). Booker name is copied from the JWT user.
         *
         *     If any hour is taken: **409 SLOT_TAKEN**.
         */
        post: {
            parameters: {
                query?: never;
                header?: {
                    /** @example Bearer {{access_token}} */
                    Authorization?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    /**
                     * @example {
                     *       "slots": [
                     *         {
                     *           "court_id": "11111111-1111-4111-8111-111111111111",
                     *           "date": "2026-08-20",
                     *           "start_time": "18:00"
                     *         },
                     *         {
                     *           "court_id": "11111111-1111-4111-8111-111111111111",
                     *           "date": "2026-08-20",
                     *           "start_time": "19:00"
                     *         }
                     *       ],
                     *       "attendee_names": [
                     *         "Ahmed Hassan",
                     *         "Omar Ali",
                     *         "Youssef Nabil",
                     *         "Karim Fathy"
                     *       ]
                     *     }
                     */
                    "application/json": {
                        slots: {
                            /** Format: uuid */
                            court_id: string;
                            /** Format: date */
                            date: string;
                            /** @example 18:00 */
                            start_time: string;
                        }[];
                        attendee_names: string[];
                    };
                };
            };
            responses: {
                /** @description 201 Created — slots held */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
                         *       "status": "held",
                         *       "court": {
                         *         "id": "11111111-1111-4111-8111-111111111111",
                         *         "name": "Court 1"
                         *       },
                         *       "date": "2026-08-20",
                         *       "start_times": [
                         *         "18:00",
                         *         "19:00"
                         *       ],
                         *       "start_time": "18:00",
                         *       "end_time": "20:00",
                         *       "booker_name": "Ahmed Hassan",
                         *       "attendee_names": [
                         *         "Ahmed Hassan",
                         *         "Omar Ali",
                         *         "Youssef Nabil",
                         *         "Karim Fathy"
                         *       ],
                         *       "price_egp": 700,
                         *       "price_cents": 70000,
                         *       "hold_expires_at": "2026-08-15T16:32:00+03:00",
                         *       "booking_code": null,
                         *       "created_at": "2026-08-15T16:22:00+03:00"
                         *     }
                         */
                        "application/json": {
                            id?: string;
                            status?: string;
                            court?: {
                                id?: string;
                                name?: string;
                            };
                            /** Format: date */
                            date?: string;
                            start_times?: string[];
                            /** Format: style */
                            start_time?: string;
                            end_time?: string;
                            booker_name?: string;
                            attendee_names?: string[];
                            price_egp?: number;
                            price_cents?: number;
                            /** Format: date-time */
                            hold_expires_at?: string;
                            booking_code?: unknown;
                            /** Format: date-time */
                            created_at?: string;
                        };
                    };
                };
                /** @description 400 Bad Request — attendees */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error?: {
                                code?: string;
                                message?: string;
                                details?: {
                                    attendee_names?: string[];
                                };
                            };
                        };
                    };
                };
                /** @description 401 Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": {
                         *         "code": "UNAUTHENTICATED",
                         *         "message": "Authentication credentials were not provided."
                         *       }
                         *     }
                         */
                        "application/json": {
                            error?: {
                                code?: string;
                                message?: string;
                            };
                        };
                    };
                };
                /** @description 409 Conflict — slot taken */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": {
                         *         "code": "SLOT_TAKEN",
                         *         "message": "This slot was just booked. Please choose another available slot."
                         *       }
                         *     }
                         */
                        "application/json": {
                            error?: {
                                code?: string;
                                message?: string;
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bookings/{booking_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example  */
                booking_id: string;
            };
            cookie?: never;
        };
        /**
         * Booking detail
         * @description Owner-only booking detail. Includes `booking_code` after payment is confirmed.
         */
        get: {
            parameters: {
                query?: never;
                header?: {
                    /** @example Bearer {{access_token}} */
                    Authorization?: string;
                };
                path: {
                    /** @example  */
                    booking_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 200 OK — owner detail */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id?: string;
                            status?: string;
                            court?: {
                                id?: string;
                                name?: string;
                            };
                            /** Format: date */
                            date?: string;
                            /** Format: style */
                            start_time?: string;
                            end_time?: string;
                            booker_name?: string;
                            attendee_names?: string[];
                            price_egp?: number;
                            price_cents?: number;
                            booking_code?: string;
                            /** Format: uri */
                            qr_payload?: string;
                            redeemed_at?: unknown;
                            /** Format: date-time */
                            created_at?: string;
                            /** Format: date-time */
                            paid_at?: string;
                        };
                    };
                };
                /** @description 401 Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": {
                         *         "code": "UNAUTHENTICATED",
                         *         "message": "Authentication credentials were not provided."
                         *       }
                         *     }
                         */
                        "application/json": {
                            error?: {
                                code?: string;
                                message?: string;
                            };
                        };
                    };
                };
                /** @description 403 Forbidden — not owner */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": {
                         *         "code": "FORBIDDEN",
                         *         "message": "You do not own this booking."
                         *       }
                         *     }
                         */
                        "application/json": {
                            error?: {
                                code?: string;
                                message?: string;
                            };
                        };
                    };
                };
                /** @description 404 Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": {
                         *         "code": "NOT_FOUND",
                         *         "message": "Booking not found."
                         *       }
                         *     }
                         */
                        "application/json": {
                            error?: {
                                code?: string;
                                message?: string;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /**
         * Cancel hold
         * @description Cancel own hold or unpaid booking and release the slot (`cancelled`). Confirmed/redeemed bookings cannot be cancelled in MVP (no refunds).
         */
        delete: {
            parameters: {
                query?: never;
                header?: {
                    /** @example Bearer {{access_token}} */
                    Authorization?: string;
                };
                path: {
                    /** @example  */
                    booking_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 200 OK — cancelled */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
                         *       "status": "cancelled",
                         *       "message": "Slot released."
                         *     }
                         */
                        "application/json": {
                            id?: string;
                            status?: string;
                            message?: string;
                        };
                    };
                };
                /** @description 401 Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": {
                         *         "code": "UNAUTHENTICATED",
                         *         "message": "Authentication credentials were not provided."
                         *       }
                         *     }
                         */
                        "application/json": {
                            error?: {
                                code?: string;
                                message?: string;
                            };
                        };
                    };
                };
                /** @description 403 Forbidden — not owner */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": {
                         *         "code": "FORBIDDEN",
                         *         "message": "You do not own this booking."
                         *       }
                         *     }
                         */
                        "application/json": {
                            error?: {
                                code?: string;
                                message?: string;
                            };
                        };
                    };
                };
                /** @description 404 Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": {
                         *         "code": "NOT_FOUND",
                         *         "message": "Booking not found."
                         *       }
                         *     }
                         */
                        "application/json": {
                            error?: {
                                code?: string;
                                message?: string;
                            };
                        };
                    };
                };
                /** @description 409 Conflict — already paid */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": {
                         *         "code": "CANNOT_CANCEL",
                         *         "message": "Paid bookings cannot be cancelled in MVP (no refunds)."
                         *       }
                         *     }
                         */
                        "application/json": {
                            error?: {
                                code?: string;
                                message?: string;
                            };
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bookings/{booking_id}/checkout": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example  */
                booking_id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start checkout
         * @description Create a Paymob Intention for this hold and return Unified Checkout URL.
         *
         *     Does **not** mark the booking paid. Status becomes `pending_payment`.
         *
         *     `special_reference` sent to Paymob = booking UUID.
         *
         *     If Paymob fails, status stays `held` so the customer can retry until TTL.
         */
        post: {
            parameters: {
                query?: never;
                header?: {
                    /** @example Bearer {{access_token}} */
                    Authorization?: string;
                };
                path: {
                    /** @example  */
                    booking_id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    /** @example {} */
                    "application/json": Record<string, never>;
                };
            };
            responses: {
                /** @description 200 OK — Paymob checkout URL */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "booking_id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
                         *       "status": "pending_payment",
                         *       "amount_egp": 350,
                         *       "amount_cents": 35000,
                         *       "currency": "EGP",
                         *       "checkout_url": "https://eg.checkout.paymob.com/?publicKey=egy_pk_test_xxxxxxxx&clientSecret=egy_csk_test_xxxxxxxx",
                         *       "paymob_intention_id": "pi_test_8f3a1c2e"
                         *     }
                         */
                        "application/json": {
                            booking_id?: string;
                            status?: string;
                            amount_egp?: number;
                            amount_cents?: number;
                            currency?: string;
                            /** Format: uri */
                            checkout_url?: string;
                            paymob_intention_id?: string;
                        };
                    };
                };
                /** @description 401 Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": {
                         *         "code": "UNAUTHENTICATED",
                         *         "message": "Authentication credentials were not provided."
                         *       }
                         *     }
                         */
                        "application/json": {
                            error?: {
                                code?: string;
                                message?: string;
                            };
                        };
                    };
                };
                /** @description 404 Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": {
                         *         "code": "NOT_FOUND",
                         *         "message": "Booking not found."
                         *       }
                         *     }
                         */
                        "application/json": {
                            error?: {
                                code?: string;
                                message?: string;
                            };
                        };
                    };
                };
                /** @description 409 Conflict — hold expired */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error?: {
                                code?: string;
                                message?: string;
                            };
                        };
                    };
                };
                /** @description 502 Bad Gateway — Paymob error */
                502: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": {
                         *         "code": "PAYMOB_ERROR",
                         *         "message": "Could not start checkout. Your slot is still held — try again."
                         *       }
                         *     }
                         */
                        "application/json": {
                            error?: {
                                code?: string;
                                message?: string;
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bookings/{booking_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example  */
                booking_id: string;
            };
            cookie?: never;
        };
        /**
         * Poll payment status
         * @description Lightweight poll for `/book/pending`. Call every 2s for up to 60s.
         *
         *     `confirmed` only after HMAC-verified webhook — never because the browser landed on Paymob's success redirect.
         */
        get: {
            parameters: {
                query?: never;
                header?: {
                    /** @example Bearer {{access_token}} */
                    Authorization?: string;
                };
                path: {
                    /** @example  */
                    booking_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 200 OK — still pending */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id?: string;
                            status?: string;
                            booking_code?: unknown;
                            /** Format: date-time */
                            hold_expires_at?: string;
                        };
                    };
                };
                /** @description 401 Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": {
                         *         "code": "UNAUTHENTICATED",
                         *         "message": "Authentication credentials were not provided."
                         *       }
                         *     }
                         */
                        "application/json": {
                            error?: {
                                code?: string;
                                message?: string;
                            };
                        };
                    };
                };
                /** @description 403 Forbidden — not owner */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": {
                         *         "code": "FORBIDDEN",
                         *         "message": "You do not own this booking."
                         *       }
                         *     }
                         */
                        "application/json": {
                            error?: {
                                code?: string;
                                message?: string;
                            };
                        };
                    };
                };
                /** @description 404 Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": {
                         *         "code": "NOT_FOUND",
                         *         "message": "Booking not found."
                         *       }
                         *     }
                         */
                        "application/json": {
                            error?: {
                                code?: string;
                                message?: string;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * My bookings
         * @description Authenticated customer's upcoming and past bookings.
         */
        get: {
            parameters: {
                query?: never;
                header?: {
                    /** @example Bearer {{access_token}} */
                    Authorization?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 200 OK — upcoming and past */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            upcoming?: {
                                id?: string;
                                status?: string;
                                court_name?: string;
                                /** Format: date */
                                date?: string;
                                /** Format: style */
                                start_time?: string;
                                end_time?: string;
                                price_egp?: number;
                                booking_code?: string;
                                period?: string;
                            }[];
                            past?: {
                                id?: string;
                                status?: string;
                                court_name?: string;
                                /** Format: date */
                                date?: string;
                                /** Format: style */
                                start_time?: string;
                                end_time?: string;
                                price_egp?: number;
                                booking_code?: string;
                                period?: string;
                            }[];
                        };
                    };
                };
                /** @description 401 Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": {
                         *         "code": "UNAUTHENTICATED",
                         *         "message": "Authentication credentials were not provided."
                         *       }
                         *     }
                         */
                        "application/json": {
                            error?: {
                                code?: string;
                                message?: string;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/staff/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Today's bookings
         * @description Paid bookings for a date (default today), focused on the next ~12 hours.
         */
        get: {
            parameters: {
                query?: {
                    /** @example {{slot_date}} */
                    date?: string;
                };
                header?: {
                    /** @example Bearer {{access_token}} */
                    Authorization?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 200 OK — paid bookings */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: date */
                            date?: string;
                            bookings?: {
                                booking_code?: string;
                                status?: string;
                                court_name?: string;
                                /** Format: style */
                                start_time?: string;
                                end_time?: string;
                                booker_name?: string;
                                redeemed_at?: unknown;
                            }[];
                        };
                    };
                };
                /** @description 401 Unauthorized — missing staff JWT */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": {
                         *         "code": "UNAUTHENTICATED",
                         *         "message": "Authentication credentials were not provided."
                         *       }
                         *     }
                         */
                        "application/json": {
                            error?: {
                                code?: string;
                                message?: string;
                            };
                        };
                    };
                };
                /** @description 403 Forbidden — customer JWT used */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": {
                         *         "code": "FORBIDDEN",
                         *         "message": "Staff token required."
                         *       }
                         *     }
                         */
                        "application/json": {
                            error?: {
                                code?: string;
                                message?: string;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/staff/passes/{booking_code}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example MGZ-7F42K */
                booking_code: string;
            };
            cookie?: never;
        };
        /**
         * Lookup pass
         * @description Staff lookup of a pass. Includes phone and Paymob transaction id.
         *
         *     `can_redeem` is true only when status is `confirmed`, it is the booking day, and it has not been redeemed.
         */
        get: {
            parameters: {
                query?: never;
                header?: {
                    /** @example Bearer {{access_token}} */
                    Authorization?: string;
                };
                path: {
                    /** @example MGZ-7F42K */
                    booking_code: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 200 OK — valid, not redeemed */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            booking_code?: string;
                            status?: string;
                            can_redeem?: boolean;
                            court?: {
                                id?: string;
                                name?: string;
                            };
                            /** Format: date */
                            date?: string;
                            /** Format: style */
                            start_time?: string;
                            end_time?: string;
                            booker_name?: string;
                            /** Format: utc-millisec */
                            booker_phone?: string;
                            attendee_names?: string[];
                            price_egp?: number;
                            paymob_transaction_id?: number;
                            redeemed_at?: unknown;
                        };
                    };
                };
                /** @description 401 Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": {
                         *         "code": "UNAUTHENTICATED",
                         *         "message": "Authentication credentials were not provided."
                         *       }
                         *     }
                         */
                        "application/json": {
                            error?: {
                                code?: string;
                                message?: string;
                            };
                        };
                    };
                };
                /** @description 404 Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": {
                         *         "code": "NOT_FOUND",
                         *         "message": "No booking for this code."
                         *       }
                         *     }
                         */
                        "application/json": {
                            error?: {
                                code?: string;
                                message?: string;
                            };
                        };
                    };
                };
                /** @description 409 Conflict — payment not confirmed */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": {
                         *         "code": "PAYMENT_NOT_CONFIRMED",
                         *         "message": "Payment not confirmed yet."
                         *       }
                         *     }
                         */
                        "application/json": {
                            error?: {
                                code?: string;
                                message?: string;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/staff/passes/{booking_code}/redeem": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example MGZ-7F42K */
                booking_code: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Redeem pass
         * @description Atomic one-time redeem: `UPDATE … WHERE booking_code=%s AND status='confirmed'`.
         *
         *     Concurrent staff taps: only one 200, the other 409 ALREADY_REDEEMED.
         */
        post: {
            parameters: {
                query?: never;
                header?: {
                    /** @example Bearer {{access_token}} */
                    Authorization?: string;
                };
                path: {
                    /** @example MGZ-7F42K */
                    booking_code: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    /** @example {} */
                    "application/json": Record<string, never>;
                };
            };
            responses: {
                /** @description 200 OK — redeemed once */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "booking_code": "MGZ-7F42K",
                         *       "status": "redeemed",
                         *       "redeemed_at": "2026-08-20T17:58:00+03:00",
                         *       "court": {
                         *         "id": "11111111-1111-4111-8111-111111111111",
                         *         "name": "Court 1"
                         *       },
                         *       "date": "2026-08-20",
                         *       "start_time": "18:00",
                         *       "end_time": "19:00",
                         *       "booker_name": "Ahmed Hassan",
                         *       "attendee_names": [
                         *         "Ahmed Hassan",
                         *         "Omar Ali",
                         *         "Youssef Nabil",
                         *         "Karim Fathy"
                         *       ]
                         *     }
                         */
                        "application/json": {
                            booking_code?: string;
                            status?: string;
                            /** Format: date-time */
                            redeemed_at?: string;
                            court?: {
                                id?: string;
                                name?: string;
                            };
                            /** Format: date */
                            date?: string;
                            /** Format: style */
                            start_time?: string;
                            end_time?: string;
                            booker_name?: string;
                            attendee_names?: string[];
                        };
                    };
                };
                /** @description 401 Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": {
                         *         "code": "UNAUTHENTICATED",
                         *         "message": "Authentication credentials were not provided."
                         *       }
                         *     }
                         */
                        "application/json": {
                            error?: {
                                code?: string;
                                message?: string;
                            };
                        };
                    };
                };
                /** @description 403 Forbidden — customer JWT used */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": {
                         *         "code": "FORBIDDEN",
                         *         "message": "Staff token required."
                         *       }
                         *     }
                         */
                        "application/json": {
                            error?: {
                                code?: string;
                                message?: string;
                            };
                        };
                    };
                };
                /** @description 404 Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": {
                         *         "code": "NOT_FOUND",
                         *         "message": "No booking for this code."
                         *       }
                         *     }
                         */
                        "application/json": {
                            error?: {
                                code?: string;
                                message?: string;
                            };
                        };
                    };
                };
                /** @description 409 Conflict — already redeemed */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error?: {
                                code?: string;
                                /** Format: style */
                                message?: string;
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks/paymob": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Payment success (placeholder HMAC)
         * @description **Source of truth for payment.** Paymob POSTs here; the browser redirect is ignored.
         *
         *     1. Verify HMAC-SHA512 with `PAYMOB_HMAC_SECRET` using Paymob's documented field order.
         *     2. Reject forged or malformed callbacks with **401 INVALID_HMAC** — do not update the booking.
         *     3. On `obj.success === true`: set status `confirmed`, issue `booking_code`, store unique `paymob_transaction_id` (idempotent on retries).
         *     4. On failure: set status `failed` and release the slot.
         *
         *     `obj.order.merchant_order_id` / `special_reference` = booking UUID.
         *
         *     **This saved success body uses a placeholder hmac.** A live 200 requires a signature computed against your `PAYMOB_HMAC_SECRET`. The invalid-hmac example is what you can send as-is to test rejection.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    /**
                     * @example {
                     *       "type": "TRANSACTION",
                     *       "obj": {
                     *         "id": 289187034,
                     *         "pending": false,
                     *         "amount_cents": 35000,
                     *         "success": true,
                     *         "is_auth": false,
                     *         "is_capture": false,
                     *         "is_standalone_payment": true,
                     *         "is_voided": false,
                     *         "is_refunded": false,
                     *         "is_3d_secure": true,
                     *         "integration_id": 123456,
                     *         "profile_id": 98765,
                     *         "has_parent_transaction": false,
                     *         "order": {
                     *           "id": 998877,
                     *           "merchant_order_id": "3fa85f64-5717-4562-b3fc-2c963f66afa6"
                     *         },
                     *         "created_at": "2026-08-15T13:24:11.123456",
                     *         "currency": "EGP",
                     *         "error_occured": false,
                     *         "owner": 111222,
                     *         "source_data": {
                     *           "pan": "2346",
                     *           "type": "card",
                     *           "sub_type": "MasterCard"
                     *         }
                     *       },
                     *       "hmac": "REPLACE_WITH_COMPUTED_HMAC_SHA512"
                     *     }
                     */
                    "application/json": {
                        type?: string;
                        obj?: {
                            id?: number;
                            pending?: boolean;
                            amount_cents?: number;
                            success?: boolean;
                            is_auth?: boolean;
                            is_capture?: boolean;
                            is_standalone_payment?: boolean;
                            is_voided?: boolean;
                            is_refunded?: boolean;
                            is_3d_secure?: boolean;
                            integration_id?: number;
                            profile_id?: number;
                            has_parent_transaction?: boolean;
                            order?: {
                                id?: number;
                                merchant_order_id?: string;
                            };
                            /** Format: style */
                            created_at?: string;
                            currency?: string;
                            error_occured?: boolean;
                            owner?: number;
                            source_data?: {
                                /** Format: utc-millisec */
                                pan?: string;
                                type?: string;
                                sub_type?: string;
                            };
                        };
                        hmac?: string;
                    };
                };
            };
            responses: {
                /** @description 200 OK — booking confirmed */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            received?: boolean;
                            booking_id?: string;
                            status?: string;
                            booking_code?: string;
                        };
                    };
                };
                /** @description 401 Unauthorized — invalid HMAC or malformed payload */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error?: {
                                code?: string;
                                message?: string;
                            };
                        };
                    };
                };
                /** @description 404 Not Found — unknown booking reference */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": {
                         *         "code": "NOT_FOUND",
                         *         "message": "No booking matches this payment reference."
                         *       }
                         *     }
                         */
                        "application/json": {
                            error?: {
                                code?: string;
                                message?: string;
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
