/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as BookIndexRouteImport } from './routes/book/index'
import { Route as BookFailedRouteImport } from './routes/book/failed'
import { Route as BookPendingRouteImport } from './routes/book/pending'
import { Route as PassCodeRouteImport } from './routes/pass/$code'
import { Route as StaffIndexRouteImport } from './routes/staff/index'
import { Route as StaffBookingsRouteImport } from './routes/staff/bookings'
import { Route as StaffLoginRouteImport } from './routes/staff/login'
import { Route as StaffPassCodeRouteImport } from './routes/staff/pass/$code'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const BookIndexRoute = BookIndexRouteImport.update({
  id: '/book/',
  path: '/book/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookFailedRoute = BookFailedRouteImport.update({
  id: '/book/failed',
  path: '/book/failed',
  getParentRoute: () => rootRouteImport,
} as any)
const BookPendingRoute = BookPendingRouteImport.update({
  id: '/book/pending',
  path: '/book/pending',
  getParentRoute: () => rootRouteImport,
} as any)
const PassCodeRoute = PassCodeRouteImport.update({
  id: '/pass/$code',
  path: '/pass/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffIndexRoute = StaffIndexRouteImport.update({
  id: '/staff/',
  path: '/staff/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffBookingsRoute = StaffBookingsRouteImport.update({
  id: '/staff/bookings',
  path: '/staff/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffLoginRoute = StaffLoginRouteImport.update({
  id: '/staff/login',
  path: '/staff/login',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffPassCodeRoute = StaffPassCodeRouteImport.update({
  id: '/staff/pass/$code',
  path: '/staff/pass/$code',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bookings': typeof BookingsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/book/failed': typeof BookFailedRoute
  '/book/pending': typeof BookPendingRoute
  '/pass/$code': typeof PassCodeRoute
  '/staff/bookings': typeof StaffBookingsRoute
  '/staff/login': typeof StaffLoginRoute
  '/book/': typeof BookIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/staff/pass/$code': typeof StaffPassCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bookings': typeof BookingsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/book/failed': typeof BookFailedRoute
  '/book/pending': typeof BookPendingRoute
  '/pass/$code': typeof PassCodeRoute
  '/staff/bookings': typeof StaffBookingsRoute
  '/staff/login': typeof StaffLoginRoute
  '/book': typeof BookIndexRoute
  '/staff': typeof StaffIndexRoute
  '/staff/pass/$code': typeof StaffPassCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bookings': typeof BookingsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/book/failed': typeof BookFailedRoute
  '/book/pending': typeof BookPendingRoute
  '/pass/$code': typeof PassCodeRoute
  '/staff/bookings': typeof StaffBookingsRoute
  '/staff/login': typeof StaffLoginRoute
  '/book/': typeof BookIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/staff/pass/$code': typeof StaffPassCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bookings'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/book/failed'
    | '/book/pending'
    | '/pass/$code'
    | '/staff/bookings'
    | '/staff/login'
    | '/book/'
    | '/staff/'
    | '/staff/pass/$code'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bookings'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/book/failed'
    | '/book/pending'
    | '/pass/$code'
    | '/staff/bookings'
    | '/staff/login'
    | '/book'
    | '/staff'
    | '/staff/pass/$code'
  id:
    | '__root__'
    | '/'
    | '/bookings'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/book/failed'
    | '/book/pending'
    | '/pass/$code'
    | '/staff/bookings'
    | '/staff/login'
    | '/book/'
    | '/staff/'
    | '/staff/pass/$code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookingsRoute: typeof BookingsRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  BookFailedRoute: typeof BookFailedRoute
  BookPendingRoute: typeof BookPendingRoute
  PassCodeRoute: typeof PassCodeRoute
  StaffBookingsRoute: typeof StaffBookingsRoute
  StaffLoginRoute: typeof StaffLoginRoute
  BookIndexRoute: typeof BookIndexRoute
  StaffIndexRoute: typeof StaffIndexRoute
  StaffPassCodeRoute: typeof StaffPassCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/': {
      id: '/book/'
      path: '/book'
      fullPath: '/book/'
      preLoaderRoute: typeof BookIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/failed': {
      id: '/book/failed'
      path: '/book/failed'
      fullPath: '/book/failed'
      preLoaderRoute: typeof BookFailedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/pending': {
      id: '/book/pending'
      path: '/book/pending'
      fullPath: '/book/pending'
      preLoaderRoute: typeof BookPendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pass/$code': {
      id: '/pass/$code'
      path: '/pass/$code'
      fullPath: '/pass/$code'
      preLoaderRoute: typeof PassCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/': {
      id: '/staff/'
      path: '/staff'
      fullPath: '/staff/'
      preLoaderRoute: typeof StaffIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/bookings': {
      id: '/staff/bookings'
      path: '/staff/bookings'
      fullPath: '/staff/bookings'
      preLoaderRoute: typeof StaffBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/login': {
      id: '/staff/login'
      path: '/staff/login'
      fullPath: '/staff/login'
      preLoaderRoute: typeof StaffLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/pass/$code': {
      id: '/staff/pass/$code'
      path: '/staff/pass/$code'
      fullPath: '/staff/pass/$code'
      preLoaderRoute: typeof StaffPassCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookingsRoute: BookingsRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  BookFailedRoute: BookFailedRoute,
  BookPendingRoute: BookPendingRoute,
  PassCodeRoute: PassCodeRoute,
  StaffBookingsRoute: StaffBookingsRoute,
  StaffLoginRoute: StaffLoginRoute,
  BookIndexRoute: BookIndexRoute,
  StaffIndexRoute: StaffIndexRoute,
  StaffPassCodeRoute: StaffPassCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
